### ISSUE TITLE
Không hiển thị các số a b c sau khi đã nhập

### ISSUE THREAD

**Issue by vuthaihoc** [colombo-trainee/hoannc005#2]
<img width="513" alt="screen shot 2016-05-20 at 10 57 37" src="https://cloud.githubusercontent.com/assets/2509658/15416839/ce91521e-1e79-11e6-81a4-4ecd26bff15c.png">
Ở các trang kết quả phải hiển thị lại các số `a`, `b`, `c` đã nhập

**Comment by hoannc54** [comment]
Đã thêm hiển thị. a check lại xem

**Comment by vuthaihoc** [comment]
Hiển thị trong input ấy
